export type Topic = 'battery' | 'noise' | 'compatibility';
export const topics = {
  battery: {
    label: '续航与通勤',
    question: '宣传的续航，能覆盖我的工作日吗？',
    strength: '优先验证',
    reason: '用户主动询问测试场景；独立测试与厂商说明可交叉参考。',
    audience: '每天带电脑出门的实习生与初入职场人群',
    title: '带电脑上班的一天，电量到底花在哪里？',
    hypothesis: '解释负载与续航的关系，能帮助用户判断是否适合自己的工作日。',
    shots: [
      '交代具体配置、电池健康、亮度、联网与电源模式',
      '记录文档、网页、会议等真实任务及持续时间',
      '展示机身与充电器的合计重量',
      '保留原始测试记录，写明适合与不适合的任务',
    ],
    counter:
      '若目标用户已理解测试条件，或主要受价格约束，补充解释未必改善决策。',
  },
  noise: {
    label: '噪音与性能',
    question: '性能不错，但在安静办公室里好用吗？',
    strength: '个案驱动',
    reason: '用户自述提供真实体验问题；尚未确认目标人群中的发生率。',
    audience: '经常在安静办公室、图书馆工作的用户',
    title: '安静办公室里，电脑的风扇会打扰我吗？',
    hypothesis:
      '展示噪音与负载的取舍，有助于降低性能预期与使用体验之间的落差。',
    shots: [
      '记录设备、系统、电源模式和环境底噪',
      '固定测量距离，比较轻办公与重负载',
      '同步记录性能变化，避免只展示静音模式',
      '区分主观感受与仪器读数，避免判定整个品牌',
    ],
    counter: '个案可能来自设置、灰尘、故障或个人敏感度；不能外推所有型号。',
  },
  compatibility: {
    label: '软件与任务',
    question: '有 AI 标签，就能跑我的工作软件吗？',
    strength: '需补用户验证',
    reason: '技术边界有官方说明；本轮未取得目标用户误购样本。',
    audience: '需要专业软件、插件或特定外设的学生与职场用户',
    title: '买电脑前，先用自己的软件完成一个任务',
    hypothesis:
      '提供具体软件、版本和任务证据，比泛化“生产力”表述更能辅助选购。',
    shots: [
      '列出处理器架构、系统与软件完整版本',
      '运行一个典型文件及必需插件',
      '检查外设、驱动和任务完成结果',
      '明确未覆盖的软件；不以 AI 标签代替兼容性测试',
    ],
    counter: '大多数日常应用可运行，不能把个别限制写成 Arm 电脑普遍不好用。',
  },
} as const;
export const evidence = [
  {
    id: 'E01',
    topic: 'battery',
    kind: '用户提问',
    title: '续航数字与办公场景的差距',
    publisher: '联想社区',
    date: '2025-11-03',
    summary: '提问者想知道所述长续航对应的测试任务，以及实际办公时的表现。',
    boundary: '单篇定向样本；不采用该帖 AI 回复中的产品数字。',
    url: 'https://club.lenovo.com.cn/thread-9445640-1-1.html',
  },
  {
    id: 'E02',
    topic: 'battery',
    kind: '独立测试',
    title: '体验需要按负载与携带条件比较',
    publisher: '香港消费者委员会',
    date: '第 586 期',
    summary:
      '32 款手提电脑测试包含电池、效能、便携等维度；携带评价考虑电源适配器。',
    boundary: '香港市场样本；不能外推大陆用户占比或当前商品排名。',
    url: 'https://www.consumer.org.hk/tc/article/586-laptops/586-laptops-test-items',
  },
  {
    id: 'E03',
    topic: 'battery',
    kind: '厂商说明',
    title: '续航结论有明确测试条件',
    publisher: 'ASUS 中国',
    date: '检索于 2026-09-08',
    summary:
      '官方产品页披露测试配置、亮度、联网及负载，并说明实际续航因使用条件而异。',
    boundary: '该机型的厂商说明，不是本项目独立实测。',
    url: 'https://www.asus.com.cn/laptops/for-home/zenbook/asus-zenbook-a16-ux3607/',
  },
  {
    id: 'E04',
    topic: 'noise',
    kind: '用户反馈',
    title: '轻办公时的风扇噪音影响体验',
    publisher: '联想社区',
    date: '2025-01-03',
    summary: '一位 ThinkPad 用户反馈办公时的噪音困扰，并尝试不同设置。',
    boundary: '未经独立检测的个案；不是型号或品牌故障率。',
    url: 'https://club.lenovo.com.cn/thread-7957358-1-1.html',
  },
  {
    id: 'E05',
    topic: 'noise',
    kind: '厂商说明',
    title: '不同场景存在性能与电源取舍',
    publisher: 'ASUS 官方支持',
    date: '更新于 2025-12-04',
    summary: 'MyASUS 可按情境调整部分电源与性能设置，支持功能因机型而异。',
    boundary: '不能据此推断某型号的实测噪音或性能。',
    url: 'https://www.asus.com.cn/support/FAQ/1045651',
  },
  {
    id: 'E06',
    topic: 'compatibility',
    kind: '技术边界',
    title: '支持大多数应用，同时保留特定限制',
    publisher: 'Microsoft Support',
    date: '检索于 2026-09-08',
    summary:
      'Windows 11 on Arm 支持大多数应用，部分驱动与反作弊游戏仍需要专门适配。',
    boundary: '须按具体软件及版本核验；不要混用 Windows 10 的旧限制。',
    url: 'https://support.microsoft.com/zh-cn/windows/experience/platform-variants/windows-arm-based-pcs-faq',
  },
  {
    id: 'E07',
    topic: 'all',
    kind: '反证',
    title: '体验抱怨不能等同于产品质量不合格',
    publisher: '国家市场监督管理总局',
    date: '2025-01-03',
    summary: '这次抽查的 26 批次笔记本电脑未发现不合格。',
    boundary: '监督抽查不覆盖所有型号，也不能代替体验评价。',
    url: 'https://www.samr.gov.cn/zw/zfxxgk/fdzdgknr/zljds/art/2025/art_fecfc8ef04bb4c17b0988e1ed82360ee.html',
  },
  {
    id: 'E08',
    topic: 'all',
    kind: '已有工具',
    title: '平台已经在做需求与内容洞察',
    publisher: '小红书灵犀',
    date: '检索于 2026-09-08',
    summary: '提供需求、受众、品牌／SPU 及搜索、笔记洞察等能力。',
    boundary: '本项目服务单次简报任务，不提供全量平台数据。',
    url: 'https://idea.xiaohongshu.com/',
  },
  {
    id: 'E09',
    topic: 'all',
    kind: '已有工具',
    title: '合作管理由平台工具承接',
    publisher: '小红书蒲公英',
    date: '检索于 2026-09-08',
    summary: '提供创作者合作及相应的数据、复盘能力。',
    boundary: '本项目不代替创作者选号、合作订单或广告投放。',
    url: 'https://pgy.xiaohongshu.com/microapp/distribution/home',
  },
];
